services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sudoku_db
    volumes:
      - sudoku_data:/var/lib/postgresql/data
    networks:
      - sudoku_network

  redis:
    image: redis:8
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sudoku_network

  auth:
    build: ./services/auth
    depends_on: 
      - postgres
    volumes:
      - ./generated:/app/generated
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/sudoku_db
    ports:
      - "50052:50052"
    networks:
      - sudoku_network
  
  solver:
    build: ./services/sudoku
    depends_on:
      - redis
    volumes:
      - ./generated:/app/generated
    ports:
      - "50051:50051"
    networks:
      - sudoku_network

  client:
    build: ./client
    depends_on: 
      - auth
      - solver
      - gateway
    volumes:
      - ./generated:/app/generated
    ports:
      - "8080:8080"
    networks:
      - sudoku_network
  
  gateway:
    build: ./api_gateway
    depends_on: 
      - auth
      - solver
    volumes:
      - ./generated:/app/generated
    ports:
      - "8000:8000"
    networks:
      - sudoku_network

networks:
  sudoku_network:

volumes:
  sudoku_data: